const api = globalThis.browser ?? globalThis.chrome;
const candidatesByTab = new Map();
const native = { port: null, pending: new Map(), seq: 0 };
const requestHeadersById = new Map();
const previewRules = { id: 2147483000 };
function tabCandidates(tabId) { if (!candidatesByTab.has(tabId)) candidatesByTab.set(tabId, new Map()); return candidatesByTab.get(tabId); }
function canonicalize(rawUrl) { try { const url = new URL(rawUrl); url.hash = ""; return url.href; } catch (_) { return rawUrl; } }
function parseContentRange(value) { const match = String(value || "").match(/^bytes\s+\d+-\d+\/(\d+)$/i); const total = Number(match?.[1]); return Number.isFinite(total) && total > 0 ? total : null; }
function classify(url, mime = "") { const lower = `${url} ${mime}`.toLowerCase(); if (lower.includes(".m3u8") || lower.includes("application/vnd.apple.mpegurl") || lower.includes("application/x-mpegurl")) return "hls"; if (lower.includes(".mpd") || lower.includes("application/dash+xml")) return "dash"; if (mime.startsWith("video/") || /\.(mp4|webm|mov|mkv|m4s)(?:$|[?#])/i.test(url)) return "video"; if (mime.startsWith("audio/") || /\.(mp3|m4a|aac|wav|flac|ogg)(?:$|[?#])/i.test(url)) return "audio"; if (mime.startsWith("image/") || /\.(jpg|jpeg|png|gif|webp)(?:$|[?#])/i.test(url)) return "image"; return null; }
function knownMime(value) { return typeof value === "string" && /^(video|audio|image)\//i.test(value) && !/\/unknown$/i.test(value); }
function mergeCandidate(existing, item) {
  const merged = { ...(existing ?? {}), ...(item ?? {}) };
  for (const [key, value] of Object.entries(existing ?? {})) if (merged[key] == null || merged[key] === "" || merged[key] === 0) merged[key] = value;
  if (knownMime(existing?.mime) && !knownMime(item?.mime)) merged.mime = existing.mime;
  if (existing?.size && !item?.size) { merged.size = existing.size; merged.sizeSource = existing.sizeSource; }
  const existingSizePriority = existing?.sizeSource === "content-range" ? 2 : existing?.sizeSource === "content-length" ? 1 : 0;
  const itemSizePriority = item?.sizeSource === "content-range" ? 2 : item?.sizeSource === "content-length" ? 1 : 0;
  if (existing?.size && (existingSizePriority > itemSizePriority || existingSizePriority === itemSizePriority && existing.size > (item?.size || 0))) { merged.size = existing.size; merged.sizeSource = existing.sizeSource; }
  if (existing?.contentDisposition && !item?.contentDisposition) merged.contentDisposition = existing.contentDisposition;
  if (existing?.requestHeaders && (!item?.requestHeaders || !Object.keys(item.requestHeaders).length)) merged.requestHeaders = existing.requestHeaders;
  return merged;
}
function addCandidate(tabId, item) { if (!Number.isInteger(tabId) || tabId < 0 || !item?.url) return; const type = classify(item.url, item.mime); if (!type) return; const canonicalUrl = canonicalize(item.url); const map = tabCandidates(tabId); const existing = map.get(canonicalUrl); const merged = mergeCandidate(existing, item); map.set(canonicalUrl, { ...merged, id: canonicalUrl, canonicalUrl, type, sizeKind: merged.sizeKind || (type === "hls" || type === "dash" ? "manifest" : "file"), detectedAt: existing?.detectedAt ?? Date.now(), lastSeenAt: Date.now() }); api.action.setBadgeText({ tabId, text: String(map.size) }).catch?.(() => {}); }
const requestHeaderOptions = ["requestHeaders", api.webRequest.OnBeforeSendHeadersOptions?.EXTRA_HEADERS].filter(Boolean);
api.webRequest.onBeforeSendHeaders.addListener(details => { const allowed = new Set(["referer", "user-agent", "cookie", "authorization", "origin"]); const headers = Object.fromEntries((details.requestHeaders ?? []).filter(header => allowed.has(header.name.toLowerCase())).map(header => [header.name.toLowerCase(), header.value ?? ""])); requestHeadersById.set(details.requestId, headers); }, { urls: ["http://*/*", "https://*/*"] }, requestHeaderOptions);
api.webRequest.onHeadersReceived.addListener(details => { const headers = Object.fromEntries((details.responseHeaders ?? []).map(header => [header.name.toLowerCase(), header.value ?? ""])); const requestHeaders = requestHeadersById.get(details.requestId) || {}; const rangeSize = parseContentRange(headers["content-range"]); const contentLength = details.statusCode === 206 ? null : Number(headers["content-length"] ?? 0) || null; addCandidate(details.tabId, { url: details.url, mime: headers["content-type"]?.split(";", 1)[0] ?? "", size: rangeSize || contentLength, sizeSource: rangeSize ? "content-range" : contentLength ? "content-length" : null, contentDisposition: headers["content-disposition"] || null, requestHeaders, referer: requestHeaders.referer || null, source: "network", requestId: details.requestId }); requestHeadersById.delete(details.requestId); }, { urls: ["http://*/*", "https://*/*"] }, ["responseHeaders"]);
api.webRequest.onErrorOccurred.addListener(details => requestHeadersById.delete(details.requestId), { urls: ["http://*/*", "https://*/*"] });
function nativeRequest(type, payload, sendResponse) { ensureNative(); if (!native.port) { sendResponse({ ok: false, error: "native_host_unavailable" }); return; } const id = `request-${++native.seq}`; native.pending.set(id, sendResponse); native.port.postMessage({ version: 1, id, type, payload }); }
async function updatePreviewHeaders(payload = {}) { if (!api.declarativeNetRequest?.updateSessionRules) return { ok: false, error: "preview_headers_unavailable" }; const headers = Object.fromEntries(Object.entries(payload.headers || {}).filter(([key, value]) => ["referer", "origin", "authorization", "cookie", "user-agent"].includes(key.toLowerCase()) && typeof value === "string" && value)); const removeRuleIds = [previewRules.id]; if (payload.action === "clear" || !payload.url || !Object.keys(headers).length) { await api.declarativeNetRequest.updateSessionRules({ removeRuleIds }); return { ok: true }; } let urlFilter; try { urlFilter = new URL(payload.url).origin; } catch (_) { return { ok: false, error: "preview_url_invalid" }; } const requestHeaders = Object.entries(headers).map(([header, value]) => ({ header: header.replace(/^(.)/, match => match.toUpperCase()), operation: "set", value })); await api.declarativeNetRequest.updateSessionRules({ removeRuleIds, addRules: [{ id: previewRules.id, priority: 1, action: { type: "modifyHeaders", requestHeaders }, condition: { urlFilter, resourceTypes: ["media", "xmlhttprequest", "image"], initiatorDomains: [api.runtime.id] } }] }); return { ok: true }; }
api.runtime.onMessage.addListener((message, sender, sendResponse) => { if (message?.type === "media.candidates") { sendResponse([...tabCandidates(message.tabId ?? sender.tab?.id).values()]); return true; } if (message?.type === "media.add") { addCandidate(sender.tab?.id, { ...message.candidate, source: message.candidate?.source || "dom" }); sendResponse({ ok: true }); return true; } if (message?.type === "probe.install") { if (!api.scripting?.executeScript || !Number.isInteger(sender.tab?.id)) { sendResponse({ ok: false, error: "page_probe_unavailable" }); return true; } api.scripting.executeScript({ target: { tabId: sender.tab.id, frameIds: [sender.frameId ?? 0] }, world: "MAIN", files: ["page-probe.js"] }).then(() => sendResponse({ ok: true })).catch(error => sendResponse({ ok: false, error: error.message })); return true; } if (message?.type === "native.connect") { ensureNative(); sendResponse({ ok: Boolean(native.port) }); return true; } if (message?.type === "task.create") { nativeRequest("task.create", message.payload, sendResponse); return true; } if (message?.type === "task.prepare") { nativeRequest("task.prepare", message.payload, sendResponse); return true; } if (message?.type === "task.list") { nativeRequest("task.list", {}, sendResponse); return true; } if (message?.type === "task.delete") { nativeRequest("task.delete", message.payload, sendResponse); return true; } if (message?.type === "path.validate") { nativeRequest("path.validate", message.payload, sendResponse); return true; } if (message?.type === "preview.headers.apply") { updatePreviewHeaders({ ...message.payload, action: "apply" }).then(sendResponse).catch(error => sendResponse({ ok: false, error: error.message })); return true; } if (message?.type === "preview.headers.clear") { updatePreviewHeaders({ action: "clear" }).then(sendResponse).catch(error => sendResponse({ ok: false, error: error.message })); return true; } return false; });
function ensureNative() { if (native.port) return; try { native.port = api.runtime.connectNative("com.streamfirefly.native"); native.port.onMessage.addListener(message => { if (message.type === "task.progress" || message.type === "task.deleted") { api.runtime.sendMessage(message).catch?.(() => {}); return; } const callback = native.pending.get(message.id); if (callback) { native.pending.delete(message.id); callback(message); } }); native.port.onDisconnect.addListener(() => { for (const callback of native.pending.values()) callback({ ok: false, error: "native_host_disconnected" }); native.pending.clear(); native.port = null; }); } catch (_) { native.port = null; } }
api.tabs.onRemoved.addListener(tabId => candidatesByTab.delete(tabId));
